apiVersion: v1
kind: Service
metadata:
  name: prueba-tecnica-service
  namespace: josue080497
spec:
  type: LoadBalancer
  selector:
    app: Prueba-tecnica
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080